### ISSUE TITLE
九宫格不能输入

### ISSUE THREAD

**Issue by cjiaw** [chinesemanbobo/PPTextField#3]
九宫格不能输入

**Comment by gaodeying998** [comment]
你好，请问你是什么手机？系统的九宫格还是其它某个输入法？？我刚测试了ios11.2 系统九宫格和百度输入法的都可以。

**Comment by AbnerPei** [comment]
稍等，晚上看看。不好意思。




| |
生而翩翩起舞，舞而惊艳乾坤。
猿农
|
|
召唤师峡谷
邮箱：chinesemanbobo@163.com
|

签名由 网易邮箱大师 定制

在2017年12月18日 15:48，gaodeying998 写道：

九宫格无法输入啊哥哥

**Comment by AbnerPei** [comment]
哥们，怎么联系你们我这边测试不到，我试了系统的还有百度输入法九宫格都，能不能联系说下




| |
生而翩翩起舞，舞而惊艳乾坤。
猿农
|
|
召唤师峡谷
邮箱：chinesemanbobo@163.com
|

签名由 网易邮箱大师 定制

在2017年12月18日 15:50，一个男人的世界，却为一个女人的爱情 写道：
稍等，晚上看看。不好意思。




| |
生而翩翩起舞，舞而惊艳乾坤。
猿农
|
|
召唤师峡谷
邮箱：chinesemanbobo@163.com
|

签名由 网易邮箱大师 定制

在2017年12月18日 15:48，gaodeying998 写道：

九宫格无法输入啊哥哥

**Comment by AbnerPei** [comment]
谁遇到九宫格的麻烦给我说下，我邮箱chinesemanbobo@163.com，尽量描述下你的使用场景，最好给个简单的抽离出来的demo,在此表示感激不尽。

**Comment by AbnerPei** [comment]
我自己并未发现,抱歉！
